name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    
    container:
      image: jonoh/rpi-docker-build:v0.1.18
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install docker client
        run: |
          apt update && apt install -y docker.io

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v4.6
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
          release_branches: main

      - name: Build images
        id: build_image
        run: |
          docker build -t rpi .
          /app/build.py --docker-image rpi --no-partitions os.img.gz boot.tar.gz &
          /app/build.py --docker-image rpi --b-partition --data-partition flash.img.gz &
          wait

      - name: Release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          files: |
            flash.img.gz
            flash.img.sha256
            os.img.gz
            os.img.sha256
            boot.tar.gz
            boot.sha256
          tag_name: ${{ steps.create_tag.outputs.new_tag }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
